version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/restaurante"
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mongo_data: